package com.dicoding.picodiploma.clubsepakbola.model;

import com.dicoding.picodiploma.clubsepakbola.R;

import java.util.ArrayList;

public class ClubData { private static String[] ClubTitles = {
        "Arsenal",
        "Aston Villa",
        "Burnley",
        "Chelsea",
        "Crystal Palace",
        "Everton",
        "Leicester City",
        "Liverpool",
        "Manchester City",
        "Manchester United",
        "Tottenham Hotspur"
};

    private static String[] ClubDetails = {
            "Arsenal merupakan salah satu klub terbaik Liga Inggris. Klub yang berbasis di kota London ini merupakan satu dari sekian klub di dunia yang memiliki banyak penggemar. Sejauh ini, Arsenal juga masih menjadi pemegang rekor sebagai tim yang mampu menjuarai Liga Inggris tanpa tersentuh satu kekalahan sekalipun. Arsenal didirikan di daerah Woolwich, bagian tenggara kota London pada 1886 dengan nama Dial Square, lalu dengan cepat berganti nama menjadi Royal Arsenal.\n" +
                    "\nAkan tetapi, pada tahun 1891 Royal Arsenal berubah nama menjadi Woolwich Arsenal. Pada tahun 1893 akhirnya mereka bergabung dengan FL atau Football League. Tim ini pindah ke Highbury pada tahun 1913 dan sudah menjadi anggota divisi dua. Seiring dengan Perang Dunia I, mereka terpilih untuk mengikuti kompetisi divisi satu yang mulai menggeliat, divisi dimana mereka berdiam sampai sekarang.\n" +
                    "\nKejayaan Arsenal di persepak bolaan Inggris pertama kali diawali oleh pelatih Herbert Chapman yang melatih pada rentang tahun 1925-35 dan berhasil menjuarai beberapa kompetisi domestik Inggris seperti Piala FA, titel Liga Utama, dan Charity Shield, sekaligus mendominasinya dan menjadikan Arsenal sebagai kekuatan paling dominan di Inggris saat itu. Perang Dunia yang kedua menghambat Arsenal dalam berkompetisi secara normal dan efektif, tetapi setelah Tom Whittaker menjadi manager, kesuksesan mulai datang lagi.\n" +
                    "\nEra 60’an, prestasi Arsenal meredup. Selama dekade itu, mereka hanya meraih 2 kali final Piala Liga, yakni pada 1968 dan 1969. Setelah Bertie Mee mengambil alih di pertengahan 60’an, mereka kembali menjuarai salah satu kompetisi piala eropa antar klub, Fairs Cup, pada musim 1969/70 dengan menghajar Anderlecht dengan skor agragat 4-3. Setelah masa tersebut, Arsenal berhasil menambah koleksi dengan beberapa gelar domestik, namun mereka tak mampu mendapat gelar dari kompetisi Eropa.\n" +
                    "\nDi era 90an, prestasi Arsenal di Eropa kembali membaik setelah pada tahun 1994, ditangan pelatih George Graham, Arsenal kembali juara di kancah Eropa dengan mengalahkan Parma FC 1-0. Arsenal berhasil kembali ke final pada tahun berikutnya, namun kali ini mereka harus takluk dari Real Zaragoza dengan skor 2-1. Kedatangan pelatih Arsene Wenger ke Arsenal pada tahun 1996 berhasil membuat tim meriam london kembali berjaya dan berhasil meruntuhkan dominasi Manchester United di Liga Utama Inggris saat itu. Arsenal juga menjadi runner-up di ajang Piala UEFA pada tahun 2000 setelah kalah melawan Galatasaray.\n " +
                    "\nPada musim 2003/04 hingga awal musim 2004/05, Arsenal berhasil mencetak rekor 49 pertandingan tak terkalahkan dan mematahkan rekor milik Nottingham Forest F.C., dengan 42 kali tanpa kekalahan, yang merupakan rekor terpanjang di dalam sejarah sepakbola Inggris. Pada musim 2005-06, Arsenal kembali meraih prestasi di kancah Eropa dengan menjadi finalis Liga Champions meski dikalahkan FC Barcelona dengan skor 2-1 di Stade de France, Paris.",
            "Aston Villa berdiri tahun 1874 dan menggunakan stadion Villa Park dari tahun 1897 hingga sekarang. Aston Villa merupakan salah satu anggota pendiri Liga Sepak Bola (Football League) dan langsung mencapai kesuksesan, mereka memenangkan lima gelar dalam waktu tujuh musim. Klub mencapai kejayaannya pada masa-masa awal abad ke-20 dengan menjuarai enam kali Liga Inggris hingga tahun 1910. Kejayaan tersebut hanya dapat diulang lagi pada musim 1980-81, ditambah gelar Piala Champions musim berikutnya 1981-82.\n" +
                    "\nMasa paling sulit pernah dialami oleh Aston Villa saat mereka harus degradasi ke Divisi Tiga pada tahun 1971. Baru setelah sepuluh tahun kemudian ketika Ron Saunders menjadi manajer, Villa kembali berhasil meraih kembali gelar Juara Liga. Musim berikutnya pada tahun 1982 di bawah asuhan manajer Tony Barton berhasil menjuarai Piala Champions UEFA dengan mengalahkan Bayern Muenchen 1-0 yang diiringi Piala Super Eropa setahun kemudian, Aston Villa adalah satu dari hanya 4 klub asal Inggris yang pernah menjuarai kompetisi papan atas Eropa tersebut.\n" +
                    "\nPada tahun 1987 mereka kembali terdegradasi namun dengan cepat kembali lagi ke level teratas. Tahun 1993 di bawah asuhan manajer Ron Atkinson berhasil menjadi runner-up Liga Inggris dan memenangkan Piala Liga masing-masing atas Manchester United pada tahun 1994 dan Leeds United pada tahun 1996.\n" +
                    "\nSetelah ditangani manajer Martin O'Neill pada tahun 2006, Villa menjadi lebih kompetitif di Liga Primer. Kebijakan O'Neill lebih dikenal dengan menggunakan banyak pemain asli Inggris Raya. Setelah dikalahkan Manchester United di Piala Liga tahun 2010 Martin O'Neill mengundurkan diri pada Agustus 2010 dan digantikan oleh mantan pelatih Liverpool Gerard Houlier. Karena masalah kesehatan akhirnya Houllier mengundurkan diri digantikan oleh mantan pelatih rival sekota the Villa Birmingham City yaitu Alex McLeish.\n" +
                    "\nSejak tahun 2006 Aston Villa dimiliki oleh pengusaha asal Amerika Serikat, yaitu Randy Lerner, yang membeli sebagian besar saham milik Doug Ellis. Setelah membeli kepemilikan klub, Lerner mengangkat dirinya sebagai presiden klub menggantikan Ellis.",
            "Burnley Football Club adalah sebuah klub sepak bola Inggris yang bermarkas di Burnley, Lancashire. Klub ini sedang bermain di Liga Utama Inggris, kasta tertinggi sepak bola inggris di musim 2016-17 setelah memenangkan liga peringkat kedua yaitu Liga Championship Inggris di musim sebelumnya. Klub ini memainkan pertandingan kandangnya di stadion Turf Moor yang berkapasitas 22.546 penonton. Seragam mereka adalah berwarna nila, sehingga mereka dijuluki Clarets. Klub ini adalah salah satu anggota penemu English Football League pada tahun 1888.\n" +
                    "\nBurnley pernah dua kali menjadi juara Liga Inggris Divisi Pertama, di musim 1920–21 dan 1959–60, pernah memenangkan Piala FA sekali, pada tahun 1914, dan pernah memenangkan Community Shield dua kali, di 1960 dan 1973.",
            "Chelsea Football Club atau lebih sering di kenal dengan nama The blues (the pensioners) merupakan klub sepak bola inggris yang bermarkas di London. Didirikan oleh H.A.Mears pada tahun 1905, dan sudah memiliki stadion sendiri yaitu Stamford bridge  terletak di London ynag berkapasitas kurang lebih 42.360 penonton.\n" +
                    "\nChelsea sendiri sudah mengisi sejarah dunia persepakbolaan inggris dan mengalami  kesuksesan beberapa kali. Pada tahun 1904 H.A. Mears mengakuisi stadion atletik Stamford Bridge dengan tujuan mengubah menjadi stadion sepak bola. Ia kemudian merencanakan pendirian sebuah klub sepak bola baru setelah tawaran yang diberikan kepada Fulham untuk menggunakan stadion tersebut ditolak.\n" +
                    "\nMengingat telah ada sebuah klub bernama Fulham, nama Chelsea yang merupakan sebuah kota kecil yang berdekatan dengan stadion dipilih sebagai nama klub baru tersebut. Nama-nama lain seperti Kensington FC, Stamford Bridge FC dan London FC sempat dipertimbangkan untuk dipilih. Chelsea didirikan pada 10 Maret 1905 di sebuah pub The Rising Sun (kini restoran The Butcher's Hook)dan pertama kali bermain pada kompetisi Football League.\n" +
                    "\nJohn Robertson seorang pemain timnas Skotlandia berusia 28 tahun saat itu dipilih merangkap jabatan pemain-manajer pertama Chelsea. Sejumlah pemain direkrut dari berbagai klub untuk memperkuat tim, seperti penjaga gawang William Fatty Foulke dari Sheffield United, Jimmy Windridge dan Bob McRoberts dari Small Heath, dan Frank Pearson dari Manchester City.",
            "Crystal Palace Football Club merupakan sebuah tim sepak bola Inggris yang bermarkas di London Borough of Croydon dan didirikan pada tahun 1905. Klub ini memainkan pertandingan kandangnya di Selhurst Park yang berkapasitas 26.309 penonton. Seragam mereka berwarna merah-biru.\n" +
                    "\nMusim 2012-13 klub ini bermain di Liga Championship Inggris. Mulai musim 2013-14, klub akan bermain di Liga Utama Inggris setelah mendapatkan promosi karena menjadi juara dalam pertandingan final play-off Liga Championship Inggris, dengan mengalahkan Watford yang berlangsung di Stadion Wembley.",
            "Pada saat didirikan klub ini bernama St. Domingo F.C. dengan tujuan agar jemaah disekitar Gereja St. Domingo dapat mengikuti olahraga di luar musim panas saat mereka jeda bermain kriket. Diawal pembentukan Everton, tim ini bermain lapangan Stanley Park tanpa ada ruang ganti dan harus membawa tiang gawang sendiri ke lapangan. Klub berubah nama menjadi Everton setahun kemudian, agar bisa menampung orang dari luar jamaah yang ingin berpartisipasi. Seragam “Royal Blue” baru dikampanyekan penggunaannya pada musim 1901/1902.\n" +
                    "\nGelar liga pertama mereka raih pada musim 1890-91. Bergabungnya Dixie Dean pada tahun 1925 mempengaruhi kesuksesan \"The Toffees\" menjuarai kompetisi musim 1927-28. Dan setelah lima gelar liga dan dua trofi Piala FA kemudian, pretasi Everton seperti berhenti dan baru bangkit lagi pada tahun 1960-an. Dua gelar liga dan satu trofi Piala FA menjadi bukti kesuksesan pada periode tersebut.\n" +
                    "\nPada tahun 1980-an, Everton kembali menikmati periode keemasan. Setelah penunjukan manajer Howard Kendall pada tahun 1981, Toffees berhasil meraih dua gelar liga pada musim 1984-85 dan 1986-87 dan satu trofi Piala FA 1984. Gelar domestik tersebut dilengkapi pula dengan trofi Piala Winners UEFA 1984-85, yang menjadi satu-satunya gelar Eropa yang pernah direngkuh Everton hingga saat ini. Akibat Tragedi Heysel, Everton tidak dapat ikut berkompetisi di Eropa. Tragedi tersebut membuat klub-klub Inggris tidak diperbolehkan mengikuti kompetisi Eropa selama lima tahun. Everton pun gagal memperoleh peluang mengulangi sukses tim-tim Inggris di kejuaraan antarklub Eropa selama periode 1980-an.\n" +
                    "\nKetika larangan tersebut dicabut oleh UEFA dan Inggris memasuki era Liga Primer, prestasi Everton mulai menurun. Setelah menjuarai Piala FA 1995, prestasi Everton cendrung menurun. Kedatangan manajer Joe Royle pada tahun 1994 sempat membuat klub disegani dan Everton sukses menduduki peringkat keenam Liga Primer musim 1995-96. Penampilan Everton kembali menurun, hingga akhirnya David Moyes datang. Manajer asal Skotlandia ini menyelamatkan Everton dari ancaman degradasi pada musim 2001-02. Tangan dingin Moyes berhasil mengangkat kembali penampilan tim.",
            "Dibentuk pada tahun 1884 oleh sekelompok pemuda Wyggeston School sebagai Leicester Fosse, klub bergabung dengan Asosiasi Sepak Bola Inggris pada tahun 1890. Sebelum pindah ke Jalan Filbert pada tahun 1891, klub bermain di lima tempat yang berbeda, termasuk Victoria Park sebelah tenggara dari pusat kota dan di Belgrave Road Cricket and Bicycle Grounds. klub juga bergabung dengan Liga Midland pada tahun 1891, dan terpilih ke Divisi Dua pada 1894 setelah finish diperingkat kedua.\n" +
                    "\nPertandingan perdana di Liga, Leicester mengalami kekalahan 4-3 di Grimsby Town, dengan kemenangan di Liga perdana mereka di minggu berikutnya, melawan Rotherham United di Filbert Street. di musim yang sama juga mereka meraih kemenangan terbesar klub hingga saat ini yakni kemenangan 13-0 atas Notts Olympic dalam pertandingan kualifikasi Piala FA. Pada musim 1907-08 klub mengakhiri sebagai runner-up Divisi II, dan meraih promosi ke Divisi utama, kasta tertinggi sepak bola Inggris. Namun, klub terdegradasi hanya dalam satu musim, dan meraih rekor kekalahan terbesar pada musim itu yakni kalah 12-0 melawan Nottingham Forest.\n" +
                    "\nPada tahun 1919, ketika Liga sepak bola kembali setelah Perang Dunia I, Leicester Fosse berhenti dalam transaksi karena kesulitan keuangan. Klub ini direformasi sebagai \"Leicester City Football Club\", sangat tepat wilayah dari Leicester baru-baru ini diberi status kota. Mengikuti perubahan nama, klub menikmati keberhasilan pada tahun 1920; di bawah manajemen Peter Hodge, yang meninggalkan Mei 1926 diganti dua bulan kemudian oleh Willie Orr, dan dengan rekor pencetak gol Arthur Chandler, mereka memenangkan gelar Divisi Dua pada 1924-25 dan raihan tertinggi kedua liga pada 1928-1929 sebagai runner-up dengan satu titik ke Sheffield Wednesday. Namun tahun 1930-an Leicester mengalami penurunan dalam kekayaan, klub terdegradasi pada 1934-35 dan, setelah promosi di 1936-1937, degradasi lagi pada 1938-1939 dan mereka menyelesaikan satu dekade di Divisi Dua.",
            "Liverpool Fc pada masa awal, klub ini didirikan pada tanggal 15 maret 1892. Klub ini didirikan setelah perseteruan antara komite Everton Fc dengan John Houlding yaitu presiden klub sekaligus pemilik stadion Anfield. Pertengkaran terjadi setelah John Houlding membeli Stadion Anfield dan menaikan harga sewa stadion kepada Everton Fc dari harga £ 100 sampai £ 250 per tahun. Everton, yang telah bermain di Anfield selama tujuh tahun, menolaknya dan terjadi perseteruan. Setelah Everton memutuskan untuk tidak melanjutkan menyewa Anfield, dan Houlding akan membuat klub sendiri yaitu Liverpool FC.\n" +
                    "\nSejarah Liverpool Fc berikutnya adalah pada masa perkembangan. Liverpool pertama kali mencapai final piala FA pertama pada tahun 1914, walaupun pada akhirnya dikalahkan Burnley 1-0. Selanjutnya, Liverpool meraih juara liga 2 musim yaitu pada tahun 1921-1922 dan musim 1922-1923. Nah, selanjutnya Liverpool Fc memasuki masa yang kurang beruntung yaitu tidak mendapatkan trofi hingga musim 1946-1947 ketika berhasil meraih gelar liga yang ke 5. Setelah berada pada divisi satu selama lebih dari 50 tahun, akhirnya Liverpool Fc jatuh dan mengalami penurunan kualitas ke divisi II pada musim 1953-54. Pada piala FA musim 1958-59, Bill Shankly ditunjuk sebagai manjer setelah Liverpool dikalahkan oleh Worcester City. Shankly melakukan perombakan besar-besaran dengan melepas 24 pemain lama dan menggunakan sebuah ruangan di Stadion Anfield untuk menggelar rapat pelatihan. Ruangan tersebut dinamakan “The Boot Room” yang sudah berhasil melahirkan manajer-manajer legendaris Liverpool di masa mendatang.\n" +
                    "\nSejarah Liverpool Fc selanjutnya memasuki masa kejayaannya. Liverpool menggapai era terbaiknya di bawah kepemimpinan manajer Bill Shankly. Pelatih tersebut kemudian menjadi legenda Liverpool. Pelatih tersebut dihormati karena berhasil membawa Liverpool kembali menjadi ke divisi satu setelah berada pada divisi dua selama 8 musim. Untuk menghormati jasanya tersebut, klub Liverpool membuat patung Bill Shankly di pintu masuk Anfield.",
            "Setelah melalui musim yang biasa-biasa saja, Manchester City menjelma menjadi sosok raksasa yang mampu menyaingi klub yang sudah lama eksis di Liga Inggris lainnya seperti Manchester united, Arsenal, hingga Liverpool. Bersama pengusaha kaya bernama Syeikh Mansour, City mampu menguasai kompetisi Liga Inggris dalam kurun waktu beberapa tahun terakhir. Manchester City adalah sebuah klub sepak bola profesional dari Inggris yang bermain di Liga Premier Inggris. Klub ini adalah klub sekota Manchester United yang bermarkas di Stadion Etihad, Manchester.\n" +
                    "\nBerdirinya Manchester City Football Club, tidak terlepas dari peran seorang wanita. Pada November 1865, Arthur Connell diangkat sebagai Kepala Gereja St.Mark’s di West Gorton, sebuah distrik di timur Manchester, Inggris. Putrinya, Anna Connell, berinisiatif dan memutuskan untuk membentuk sebuah asosiasi yang mendorong para pemuda paroki untuk berolahraga.\n" +
                    "\nSaat itu, tingkat kejahatan dan pengangguran sangat tinggi. Mereka percaya bahwa olahraga dapat menyatukan dan mengurangi kejahatan di timur Manchester. Tahun 1868 sudah terbentuk Tim Kriket Gereja St.Mark’s, dan pada tahun 1875, tim kriket mulai menambahkan permainan sepakbola pada perkumpulannya. Akhirnya, tepat pada tahun 1880 para pemain kriket membentuk tim sepak bola dengan nama St.Marks West Gordon dibawah bimbingan William Beastow dan Anna Connell.\n" +
                    "\nTahun 1887, mereka pindah ke markas yang baru di Hyde Road, Ardwick. Nama klub pun berubah menjadi Ardwick A.F.C. untuk menyesuaikan letak barunya. Kemudian, Ardwick mulai ikut berkompetisi di divisi 2 Football League tahun 1892. Setahun setelahnya, tepat di musim 1893/94, masalah keuangan mulai membelit klub. Setelah menjalani beberapa pertemuan, akhirnya mereka berganti nama menjadi Manchester City Football Club.",
            "Manchester United adalah klub Inggris yang paling mendunia. Mereka adalah klub Inggris pertama yang bermain di Piala Eropa dan klub Inggris pertama yang memenangkannya, dan mereka adalah satu-satunya klub Inggris yang pernah menjadi juara dunia Piala Dunia antar Klub.\n" +
                    "\nKlub ini didirikan pada 1878 dengan nama Newton Heath LYR Football Club oleh pekerja di Lancashire dan Yorkshire Railway Depot. Mereka bermain di Liga Sepakbola untuk pertama kalinya pada tahun 1892, namun terdegradasi dua tahun kemudian. Klub ini menjadi Manchester United pada tahun 1902, ketika sekelompok pengusaha lokal mengambil alih. Saat itulah mereka mengadopsi baju merah yang akan menjadi sangat dikenal hingga saat ini.\n" +
                    "\nKlub ini menjuarai liga kali pertama mereka di bawah Ernest Mangnall pada tahun 1908 dan 1911, menambahkan Piala FA pertama mereka pada tahun 1909. Mangnall kemudian meninggalkan United untuk bergabung dengan Manchester City pada tahun 1911.",
            "Tottenham Hotspur Football Club adalah klub sepak bola yang berasal dari Tottenham, sebuah daerah yang berada di wilayah utara London. Mereka juga dikenal sebagai Spurs, The Spurs dan Tottenham, sementara penggemar mereka memberi mereka nama the Lilywhites karena seragam tradisional mereka yang berwarna putih.\n" +
                    "\nDidirikan pada tahun 1882, Tottenham memenangkan Piala FA untuk pertama kalinya pada tahun 1901, dan menjadi satu-satunya klub non-Liga yang menjuarai Piala FA, sejak dibentuknya The Football League. Pada musim 1960-61, Tottenham adalah klub pertama pada abad ke-20 yang meraih gelar ganda sebagai juara Liga dan Piala FA. Setelah berhasil mempertahankan Piala FA pada tahun 1962, Tottenham menjadi klub Inggris pertama yang memenangkan kompetisi klub UEFA dengan menjadi juara Piala Winners UEFA pada tahun 1963. Piala FA yang ketiga kalinya pada tahun 1960-an, dimenangkan pada tahun 1967.\n" +
                    "\nPada 1970-an, Tottenham memenangkan dua Piala Liga yaitu pada tahun 1971 dan 1973. Pada tahun 1972, menjadi klub pertama yang menjadi juara Piala UEFA sejak dibentuk pada tahun 1971 dan menjadi klub Inggris pertama yang memenangkan dua piala utama Eropa yang berbeda. Pada 1980-an, Spurs memenangkan beberapa piala dengan Piala FA sebanyak dua kali, FA Community Shield dan Piala UEFA pada tahun 1984. Pada 1990-an, klub memenangkan Piala FA dan Piala Liga. Ketika memenangkan Piala Liga sekali lagi pada tahun 2008, menjadikan mereka klub yang telah memenangkan trofi utama di setiap enam dekade terakhir - sebuah prestasi yang sama dengan Manchester United.\n" +
                    "\nKlub ini bermarkas di Stadion Tottenham Hotspur Motto dari klub ini adalah Audere est Facere yang merupakan bahasa Latin yang sering diterjemahkan ke dalam bahasa Inggris sebagai \"To Dare is To Do\". Spurs memiliki perseteruan yang cukup tua dengan klub sekota, Arsenal, dan pertandingan antara Spurs dengan Arsenal terkenal dengan nama Derby London Utara."
    };

    private static int[] ClubImages = {
            R.drawable.arsenal,
            R.drawable.aston,
            R.drawable.burnley,
            R.drawable.chelsea,
            R.drawable.crystal,
            R.drawable.everton,
            R.drawable.leicester,
            R.drawable.liverpool,
            R.drawable.mc,
            R.drawable.mu,
            R.drawable.tottenham
    };

    public static ArrayList<Club> getListData() {
        ArrayList<Club> list = new ArrayList<>();
        for (int position = 0; position < ClubTitles.length; position++ ){
            Club Club = new Club();
            Club.setTitle(ClubTitles[position]);
            Club.setDetail(ClubDetails[position]);
            Club.setPhoto(ClubImages[position]);
            list.add(Club);
        }
        return list;
    }

}
